# Author: Mazhar Ahmed, CTO, Oceanize Inc
# All rights reserved. Copyright (c) Oceanize Inc
version: '3'
services:
  app:
    image: oceanize/flask_app:latest
    container_name: flask_app
    restart: unless-stopped
    #labels:
    #  project: "flask"
    #  day: "9 Sep 2019"
    #build:
    #  # build the image from Dockerfile
    #  context: .
    #  dockerfile: Dockerfile
    #environment:
    #  # set database, memcached etc credentials
    #  DB_HOST: mysql
    #  DB_NAME: flask
    #  DB_USER: flask
    #  DB_PASSWORD: slimdingo85
    volumes:
      - ./app:/app
    ports:
      # bind on our 5000 port because most people have 80, 8080 already bound
      - "5000:5000"
